sudo: false
language: python
python:
  - "3.5"
  - "3.4"
  - "3.3"
  - "3.2"
  - "2.7"
  - "pypy"
env:
  - DJANGO="Django>=1.8,<1.9"
  - DJANGO="Django>=1.9,<1.10"
matrix:
  exclude:
    - env: DJANGO="Django>=1.8,<1.9"
      python: "3.5"
    - env: DJANGO="Django>=1.9,<1.10"
      python: "3.2"
    - env: DJANGO="Django>=1.9,<1.10"
      python: "3.3"

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install $DJANGO mock-django==0.6.9
# command to run tests, e.g. python setup.py test
script: cd tests/ && ./runtests.sh

# Run on travis' container infrastructure
sudo: false
